### ISSUE TITLE
修改D3Json遇到的的问题

### ISSUE THREAD

**Issue by rtspVideoview** [mozhenhau/D3Json#1]
您好！我是之前给您发邮件的人，根据您的提示，为了解决Bean里面包含Array<Bean>，我进行了修改
private class func addExtension(key:String,type:Any.Type,obj:AnyObject,dic:AnyObject){
        switch type {
        case _ as TreeBean.Type:
            obj.setValue(jsonToModel(dic.objectForKey(key), objc: TreeBean()),forKey:key)
        case _ as CauseBean.Type:
            obj.setValue(jsonToModel(dic.objectForKey(key), objc: CauseBean()),forKey:key)
        case _ as CheckBean.Type:
            obj.setValue(jsonToModel(dic.objectForKey(key), objc: CheckBean()),forKey:key)
        case _ as FaultTreatBean.Type:
            obj.setValue(jsonToModel(dic.objectForKey(key), objc: FaultTreatBean()),forKey:key)
        case _ as Array<FaultTreatBean>.Type:
            obj.setValue(jsonToModelList(dic.objectForKey(key), objc: FaultTreatBean()), forKey: key)
        case _ as SolutionBean.Type:
            obj.setValue(jsonToModel(dic.objectForKey(key), objc: SolutionBean()),forKey:key)
        default:     //unknow
            println("key:(key),unknow,sure that you hava init")
        }
    }
但是，obj.setValue(jsonToModelList(dic.objectForKey(key), objc: FaultTreatBean()), forKey: key)这句会报错，'cannot invoke 'jsonToModelList' with an argument list of type'(AnyObject?,objc:FaultTreatBean)'

**Comment by mozhenhau** [comment]
try this:
case _ as Job.Type:
            obj.setValue(jsonToModel(dic.objectForKey(key), objc: Job()),forKey:key)

```
    case _ as Array<Job>.Type:
        var value:Array<Job> = jsonToModelList((dic.objectForKey(key) as? NSArray), objc: Job())
        obj.setValue(value, forKey: key)
```

**Comment by rtspVideoview** [comment]
I have succeed,thank you

**Comment by angelen10** [comment]
这样做不用通用呀，这个方法能不能在需要的model类中写呢？

**Comment by mozhenhau** [comment]
@angelen10 没想到这个项目挺多人关注的，已修改，利用NSClassFromString的方法进行实例化，就不用每个自定义都需要写扩展了。如果你有更好的想法，欢迎Pull Request
