### ISSUE TITLE
当遇到的实体有嵌套的时候无法运行？

### ISSUE THREAD

**Issue by angelen10** [mozhenhau/D3Json#2]
``` java
class A {
    var a_id = ""
    var b = B()

}

class B {
    var b_id = ""
    var c = C()
}

class C {
    var c_id = ""
}
```

我请求回来的是A实体，其中A实体有B实体的实例，B实体有C实体的实例。

**Comment by mozhenhau** [comment]
@angelen10  
like this :

@objc(A)
class A:NSObject {
    var a_id = ""
    var b:B!
}

@objc(B)
class B :NSObject{
    var b_id = ""
    var c:C!
}

@objc(C)
class C:NSObject {
    var c_id = ""
}

**Comment by angelen10** [comment]
@mozhenhau thx
