### ISSUE TITLE
请更新下 cocoapods repo

### ISSUE THREAD

**Issue by liuyu827** [mozhenhau/D3Json#3]
现在 cocoapods repo 的版本还是1.0.2 麻烦更新下 
谢谢

**Comment by mozhenhau** [comment]
迟点更新，已想到解决swift2.0不能动态实例化的解决方法

**Comment by zhenyiyi** [comment]
发现 有时候数组的对应的没有映射出来，得到的数组为空。找了半天，没有发现原因，打印对应的key没有打印出来，

**Comment by zhenyiyi** [comment]
请求结果1 {
    Code = 0;
    Data =     (
                {
            Amount = 375;
            BeginTime = "2015-10-10T13:28:56";
            Countdown = 37190;
            EndTime = "2015-10-14T15:27:33";
            Gold = 50;
            Introduction = "\U7ecf\U5178\U5c0f\U725b\U9020\U578b\Uff0c25\U74e65A\U5feb\U901f\U5145\U7535\Uff0c\U8fdb\U53e3\U9632\U706b\U6750\U8d28";
            PromotionsId = 164;
            PromotionsStatus = 5;
            PromotionsType = 0;
            Recommend = "<null>";
            RelationId = 10000022;
            RelationStatus = 2;
            ShareType = 0;
            Thumbnails =             (
                "ad/10000022/c7376cdc-8328-4587-8be1-9d51ce8fa869.jpg"
            );
            Title = "\U6469\U7c73\U58eb\U516c\U725b\U667a\U80fd\U6570\U7801\U5145\U7535\U5668\Uff0840W \Uff09\U9ec4\U8272";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-28T15:10:24";
            Countdown = 1504864;
            EndTime = "2015-10-31T15:08:47";
            Gold = 1;
            Introduction = "\U826f\U54c1\U94fa\U5b50\U5fae\U5546\U57ce\Uff0c\U5e26\U4f60\U8fdb\U884c\U4e00\U573a\U7f8e\U98df\U65c5\U884c~~";
            PromotionsId = 156;
            PromotionsStatus = 5;
            PromotionsType = 1;
            Recommend = "<null>";
            RelationId = 43;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ad/43/77fa4ceb-e995-491b-8957-694b34d88357.jpg"
            );
            Title = "\U8f6c\U53d1\U9001\U5143\U5b9d\U2014\U2014\U826f\U54c1\U94fa\U5b50";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "<h3 class=\"hdtitle\">\U8be6\U60c5</h3><div class=\"slider\"><ul id=\"slider\"><li style=\"display:block\"><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_1.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_2.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_3.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_4.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_5.jpg\"/></a></li></ul><div id=\"pagenavi\"><a href=\"javascript:void(0);\" class=\"active\"></a><a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a>  </div></div><div class=\"clear\"></div><div class=\"clear\"></div><h3 class=\"hdtitle\">\U4fe1\U606f</h3><div class=\"cpminfo\"><p>\U540d\U79f0: <b>\U8611\U83c7\U8857</b></p><p><span>\U7c7b\U522b: </span><span >\U751f\U6d3b</span></p><p><span>\U7248\U672c: </span><span>7.2.1.150902004</span></p><p><span>\U5927\U5c0f: </span>72.4MB</p><p><span>\U8bed\U8a00: </span>\U65e5\U8bed, \U7b80\U4f53\U4e2d\U6587, \U82f1\U8bed, \U97e9\U8bed</p><p><span>\U66f4\U65b0\U65e5\U671f: </span><span >2015\U5e7409\U670810\U65e5</span></p><p><span>\U5f00\U53d1\U5546: </span><span>Juangua network Co., Ltd. Hangzhou \U00a9 2015 mogujie.com</span></p><div class=\"content\"><p><b>\U517c\U5bb9\U6027:</b> \U9700\U8981 iOS 7.0 \U6216\U66f4\U9ad8\U7248\U672c\U3002\U4e0e iPhone\U3001iPad\U3001iPod touch \U517c\U5bb9\U3002</p><p>>>>\U674e\U6613\U5cf0\U91cd\U78c5\U4ee3\U8a00\U8611\U83c7\U8857\Uff0c\U201c\U5cf0\U201d\U72c2\U6765\U88ad\Uff0c\U4e3a\U4f60\U201c\U5cf0\U201d\U72c2\Uff0c\U5cf0\U5cf0\U5728\U8611\U83c7\U8857\U7b49\U4f60\U4e00\U8d77\U901b~\U8d85\U5e05\U8d85\U840c\U5f69\U86cb\U7b49\U4f60\U6765\U53d1\U73b0\Uff01</p><p>>>>\U674e\U6613\U5cf0\U7c89\U4e1d\U4e13\U533a\Uff0c\U6bcf\U65e5\U62bd\U5956\U4e0d\U505c\U6b47\Uff0c\U9650\U91cf\U7248\U624b\U529e\U3001DIY\U624b\U673a\U58f3\U3001\U7279\U5236\U8d34\U7eb8\U3001\U4e13\U5c5e\U65e5\U5386......\U90fd\U5728\U7b49\U4f60\U6765\U9886\U53d6\U3002</p><p>>>>\U6700\U65b0\U5cf0\U5cf0\U5e7f\U544a\U7247\Uff0c\U8611\U83c7\U8857\U5185\U9996\U53d1\Uff01\U8d76\U7d27\U4e0b\U8f7d\U5c16\U53eb\U5427\Uff01</p></div></div>";
            PromotionsId = 142;
            PromotionsStatus = 5;
            PromotionsType = 3;
            Recommend = "<null>";
            RelationId = 37;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ky/mogujie_608x259.jpg"
            );
            Title = "\U8611\U83c7\U8857-\U6211\U7684\U4e70\U624b\U8857\Uff0c\U6bcf\U5929\U81f3\U5c11\U7231\U4e00\U6b21";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "\U5151\U4e86\U4e48\U65b0\U9896\U79fb\U52a8\U4e92\U8054\U7f51\U5956\U52b1App\Uff0c\U5f00\U542f\U201c\U5151\U201d\U7684\U751f\U6d3b\Uff01";
            PromotionsId = 134;
            PromotionsStatus = 5;
            PromotionsType = 1;
            Recommend = "<null>";
            RelationId = 33;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ad/33/f6ad6b08-675f-4848-aaf4-78c410fc2065.jpg"
            );
            Title = "\U8f6c\U53d1\U9001\U5143\U5b9d";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "<h3 class=\"hdtitle\">\U8be6\U60c5</h3><div class=\"slider\"><ul id=\"slider\"><li style=\"display:block\"><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_1.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_2.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_3.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_4.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_5.jpg\"/></a></li></ul><div id=\"pagenavi\"><a href=\"javascript:void(0);\" class=\"active\"></a><a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a>  </div></div><div class=\"clear\"></div><div class=\"clear\"></div><h3 class=\"hdtitle\">\U4fe1\U606f</h3><div class=\"cpminfo\"><p> \U540d\U79f0: <b>\U9014\U725b</b></p><p>\U7c7b\U522b: \U65c5\U6e38</p><p>\U7248\U672c: 7.0.0</p><p>\U5927\U5c0f: 63.7MB</p><p>\U8bed\U8a00: \U7b80\U4f53\U4e2d\U6587, \U82f1\U8bed</p><p>\U66f4\U65b0\U65e5\U671f: 2015\U5e7409\U670815\U65e5</p><p>\U5f00\U53d1\U5546: Tuniu Co. Ltd \U00a9 \U9014\U725b\U65c5\U6e38</p><div class=\"content\"><p><b>\U517c\U5bb9\U6027:</b> \U9700\U8981 iOS 7.0 \U6216\U66f4\U9ad8\U7248\U672c\U3002\U4e0e iPhone\U3001iPad\U3001iPod touch \U517c\U5bb9\U3002</p><p>\U9014\U725b\U65c5\U6e38\U2014\U2014\U8ba9\U65c5\U6e38\U66f4\U7b80\U5355\Uff0c\U8ba9\U51fa\U884c\U66f4\U65b9\U4fbf\Uff01</p></div></div>";
            PromotionsId = 143;
            PromotionsStatus = 5;
            PromotionsType = 3;
            Recommend = "<null>";
            RelationId = 38;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ky/tuniu_608x259.jpg"
            );
            Title = "\U9014\U725b\U65c5\U6e38-\U4e2d\U56fd\U597d\U58f0\U97f3\U5b98\U65b9\U6307\U5b9a\U65c5\U6e38\U7f51\U7ad9";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "<h3 class=\"hdtitle\">\U8be6\U60c5</h3><div class=\"slider\"><ul id=\"slider\"><li style=\"display:block\"><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_1.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_2.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_3.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_4.jpg\"/></a></li></ul><div id=\"pagenavi\"><a href=\"javascript:void(0);\" class=\"active\"></a><a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a>  </div></div><div class=\"clear\"></div><div class=\"clear\"></div><h3 class=\"hdtitle\">\U4fe1\U606f</h3><div class=\"cpminfo\"><p>\U540d\U79f0: <b>\U4f4f\U767e\U5bb6</b></p><p><span>\U7c7b\U522b: </span><span >\U65c5\U6e38</span></p><p><span>\U7248\U672c: </span><span>2.6</span></p><p><span>\U5927\U5c0f: </span>21.5MB</p><p><span>\U8bed\U8a00: </span>\U7b80\U4f53\U4e2d\U6587, \U82f1\U8bed</p><p><span>\U66f4\U65b0\U65e5\U671f: </span><span >2015\U5e7409\U670815\U65e5</span></p><p><span>\U5f00\U53d1\U5546: </span><span>ZBJ Co., Ltd.\U00a9 2015 ZBJ Co., Ltd.</span></p><div class=\"content\"><p><b>\U517c\U5bb9\U6027:</b>  \U9700\U8981 iOS 7.0 \U6216\U66f4\U9ad8\U7248\U672c\U3002\U4e0e iPhone\U3001iPad\U3001iPod touch \U517c\U5bb9\U3002</p><p style=\"text-indent:2em;\">\U4f4f\U767e\U5bb6\U65c5\U6e38\U7ba1\U5bb6(omeome),\U662f\U4e13\U4e3a\U56fd\U4eba\U8bbe\U8ba1\U7684\U5883\U5916\U65c5\U6e38\U77ed\U79df\U670d\U52a1\U5e94\U7528\U3002<br/>           \U4f4f\U767e\U5bb6\U5728\U5168\U740360\U591a\U4e2a\U56fd\U5bb6\U548c\U5730\U533a\U62e5\U6709\U6570\U767e\U4e07\U5957\U4f18\U8d28\U623f\U6e90\Uff0c\U5168\U9762\U8986\U76d6\U4e86\U51fa\U5883\U65c5\U6e38\U7684\U9700\U6c42\U3002<br/>           \U4e0d\U65ad\U66f4\U65b0\U7684\U51fa\U5883\U6e38\U65b0\U73a9\U6cd5\Uff0c\U6253\U9020\U539f\U6c41\U539f\U5473\U7684\U6d77\U5916\U751f\U6d3b\U4f53\U9a8c\U3002</p></div></div>";
            PromotionsId = 144;
            PromotionsStatus = 5;
            PromotionsType = 3;
            Recommend = "<null>";
            RelationId = 39;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ky/zhubaijia_608x259.jpg"
            );
            Title = "\U4f4f\U767e\U5bb6-\U51fa\U5883\U6e38\U7cbe\U9009\U77ed\U79df-\U81ea\U7531\U884c\U6c11\U5bbf\U4e13\U5bb6-\U65c5\U884c\U7f8e\U98df\U653b\U7565\U6307\U5357";
        }
    );
    Msg = "\U83b7\U53d6\U6d3b\U52a8\U9996\U9875\U4fe1\U606f";
} 
请求的状态： 200   请求的URL http://earn.duileme.cn/Promotions/IOSHome 请求的参数  {
    Appid = MC001;
    LoginToken = 9c97cb246c49929c690dc8a148481ab2;
    Sign = 654c5b989c4dd6bd66d48c2aef5344e6;
    version = "1.1.9";
} 
请求结果1 {
    Code = 0;
    Data =     (
                {
            Amount = 375;
            BeginTime = "2015-10-10T13:28:56";
            Countdown = 37190;
            EndTime = "2015-10-14T15:27:33";
            Gold = 50;
            Introduction = "\U7ecf\U5178\U5c0f\U725b\U9020\U578b\Uff0c25\U74e65A\U5feb\U901f\U5145\U7535\Uff0c\U8fdb\U53e3\U9632\U706b\U6750\U8d28";
            PromotionsId = 164;
            PromotionsStatus = 5;
            PromotionsType = 0;
            Recommend = "<null>";
            RelationId = 10000022;
            RelationStatus = 2;
            ShareType = 0;
            Thumbnails =             (
                "ad/10000022/c7376cdc-8328-4587-8be1-9d51ce8fa869.jpg"
            );
            Title = "\U6469\U7c73\U58eb\U516c\U725b\U667a\U80fd\U6570\U7801\U5145\U7535\U5668\Uff0840W \Uff09\U9ec4\U8272";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-28T15:10:24";
            Countdown = 1504864;
            EndTime = "2015-10-31T15:08:47";
            Gold = 1;
            Introduction = "\U826f\U54c1\U94fa\U5b50\U5fae\U5546\U57ce\Uff0c\U5e26\U4f60\U8fdb\U884c\U4e00\U573a\U7f8e\U98df\U65c5\U884c~~";
            PromotionsId = 156;
            PromotionsStatus = 5;
            PromotionsType = 1;
            Recommend = "<null>";
            RelationId = 43;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ad/43/77fa4ceb-e995-491b-8957-694b34d88357.jpg"
            );
            Title = "\U8f6c\U53d1\U9001\U5143\U5b9d\U2014\U2014\U826f\U54c1\U94fa\U5b50";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "<h3 class=\"hdtitle\">\U8be6\U60c5</h3><div class=\"slider\"><ul id=\"slider\"><li style=\"display:block\"><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_1.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_2.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_3.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_4.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/mogujie/mogu_5.jpg\"/></a></li></ul><div id=\"pagenavi\"><a href=\"javascript:void(0);\" class=\"active\"></a><a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a>  </div></div><div class=\"clear\"></div><div class=\"clear\"></div><h3 class=\"hdtitle\">\U4fe1\U606f</h3><div class=\"cpminfo\"><p>\U540d\U79f0: <b>\U8611\U83c7\U8857</b></p><p><span>\U7c7b\U522b: </span><span >\U751f\U6d3b</span></p><p><span>\U7248\U672c: </span><span>7.2.1.150902004</span></p><p><span>\U5927\U5c0f: </span>72.4MB</p><p><span>\U8bed\U8a00: </span>\U65e5\U8bed, \U7b80\U4f53\U4e2d\U6587, \U82f1\U8bed, \U97e9\U8bed</p><p><span>\U66f4\U65b0\U65e5\U671f: </span><span >2015\U5e7409\U670810\U65e5</span></p><p><span>\U5f00\U53d1\U5546: </span><span>Juangua network Co., Ltd. Hangzhou \U00a9 2015 mogujie.com</span></p><div class=\"content\"><p><b>\U517c\U5bb9\U6027:</b> \U9700\U8981 iOS 7.0 \U6216\U66f4\U9ad8\U7248\U672c\U3002\U4e0e iPhone\U3001iPad\U3001iPod touch \U517c\U5bb9\U3002</p><p>>>>\U674e\U6613\U5cf0\U91cd\U78c5\U4ee3\U8a00\U8611\U83c7\U8857\Uff0c\U201c\U5cf0\U201d\U72c2\U6765\U88ad\Uff0c\U4e3a\U4f60\U201c\U5cf0\U201d\U72c2\Uff0c\U5cf0\U5cf0\U5728\U8611\U83c7\U8857\U7b49\U4f60\U4e00\U8d77\U901b~\U8d85\U5e05\U8d85\U840c\U5f69\U86cb\U7b49\U4f60\U6765\U53d1\U73b0\Uff01</p><p>>>>\U674e\U6613\U5cf0\U7c89\U4e1d\U4e13\U533a\Uff0c\U6bcf\U65e5\U62bd\U5956\U4e0d\U505c\U6b47\Uff0c\U9650\U91cf\U7248\U624b\U529e\U3001DIY\U624b\U673a\U58f3\U3001\U7279\U5236\U8d34\U7eb8\U3001\U4e13\U5c5e\U65e5\U5386......\U90fd\U5728\U7b49\U4f60\U6765\U9886\U53d6\U3002</p><p>>>>\U6700\U65b0\U5cf0\U5cf0\U5e7f\U544a\U7247\Uff0c\U8611\U83c7\U8857\U5185\U9996\U53d1\Uff01\U8d76\U7d27\U4e0b\U8f7d\U5c16\U53eb\U5427\Uff01</p></div></div>";
            PromotionsId = 142;
            PromotionsStatus = 5;
            PromotionsType = 3;
            Recommend = "<null>";
            RelationId = 37;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ky/mogujie_608x259.jpg"
            );
            Title = "\U8611\U83c7\U8857-\U6211\U7684\U4e70\U624b\U8857\Uff0c\U6bcf\U5929\U81f3\U5c11\U7231\U4e00\U6b21";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "\U5151\U4e86\U4e48\U65b0\U9896\U79fb\U52a8\U4e92\U8054\U7f51\U5956\U52b1App\Uff0c\U5f00\U542f\U201c\U5151\U201d\U7684\U751f\U6d3b\Uff01";
            PromotionsId = 134;
            PromotionsStatus = 5;
            PromotionsType = 1;
            Recommend = "<null>";
            RelationId = 33;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ad/33/f6ad6b08-675f-4848-aaf4-78c410fc2065.jpg"
            );
            Title = "\U8f6c\U53d1\U9001\U5143\U5b9d";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "<h3 class=\"hdtitle\">\U8be6\U60c5</h3><div class=\"slider\"><ul id=\"slider\"><li style=\"display:block\"><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_1.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_2.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_3.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_4.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/tuniu/tuniu_5.jpg\"/></a></li></ul><div id=\"pagenavi\"><a href=\"javascript:void(0);\" class=\"active\"></a><a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a>  </div></div><div class=\"clear\"></div><div class=\"clear\"></div><h3 class=\"hdtitle\">\U4fe1\U606f</h3><div class=\"cpminfo\"><p> \U540d\U79f0: <b>\U9014\U725b</b></p><p>\U7c7b\U522b: \U65c5\U6e38</p><p>\U7248\U672c: 7.0.0</p><p>\U5927\U5c0f: 63.7MB</p><p>\U8bed\U8a00: \U7b80\U4f53\U4e2d\U6587, \U82f1\U8bed</p><p>\U66f4\U65b0\U65e5\U671f: 2015\U5e7409\U670815\U65e5</p><p>\U5f00\U53d1\U5546: Tuniu Co. Ltd \U00a9 \U9014\U725b\U65c5\U6e38</p><div class=\"content\"><p><b>\U517c\U5bb9\U6027:</b> \U9700\U8981 iOS 7.0 \U6216\U66f4\U9ad8\U7248\U672c\U3002\U4e0e iPhone\U3001iPad\U3001iPod touch \U517c\U5bb9\U3002</p><p>\U9014\U725b\U65c5\U6e38\U2014\U2014\U8ba9\U65c5\U6e38\U66f4\U7b80\U5355\Uff0c\U8ba9\U51fa\U884c\U66f4\U65b9\U4fbf\Uff01</p></div></div>";
            PromotionsId = 143;
            PromotionsStatus = 5;
            PromotionsType = 3;
            Recommend = "<null>";
            RelationId = 38;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ky/tuniu_608x259.jpg"
            );
            Title = "\U9014\U725b\U65c5\U6e38-\U4e2d\U56fd\U597d\U58f0\U97f3\U5b98\U65b9\U6307\U5b9a\U65c5\U6e38\U7f51\U7ad9";
        },
                {
            Amount = 0;
            BeginTime = "2015-09-18T09:45:11";
            Countdown = 189386;
            EndTime = "2015-10-16T09:44:09";
            Gold = 2;
            Introduction = "<h3 class=\"hdtitle\">\U8be6\U60c5</h3><div class=\"slider\"><ul id=\"slider\"><li style=\"display:block\"><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_1.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_2.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_3.jpg\"/></a></li><li><a href=\"javascript:void(0);\"><img src=\"http://image.duileme.cn/ky/zhubaijia/zhubaijia_4.jpg\"/></a></li></ul><div id=\"pagenavi\"><a href=\"javascript:void(0);\" class=\"active\"></a><a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a> <a href=\"javascript:void(0);\" ></a>  </div></div><div class=\"clear\"></div><div class=\"clear\"></div><h3 class=\"hdtitle\">\U4fe1\U606f</h3><div class=\"cpminfo\"><p>\U540d\U79f0: <b>\U4f4f\U767e\U5bb6</b></p><p><span>\U7c7b\U522b: </span><span >\U65c5\U6e38</span></p><p><span>\U7248\U672c: </span><span>2.6</span></p><p><span>\U5927\U5c0f: </span>21.5MB</p><p><span>\U8bed\U8a00: </span>\U7b80\U4f53\U4e2d\U6587, \U82f1\U8bed</p><p><span>\U66f4\U65b0\U65e5\U671f: </span><span >2015\U5e7409\U670815\U65e5</span></p><p><span>\U5f00\U53d1\U5546: </span><span>ZBJ Co., Ltd.\U00a9 2015 ZBJ Co., Ltd.</span></p><div class=\"content\"><p><b>\U517c\U5bb9\U6027:</b>  \U9700\U8981 iOS 7.0 \U6216\U66f4\U9ad8\U7248\U672c\U3002\U4e0e iPhone\U3001iPad\U3001iPod touch \U517c\U5bb9\U3002</p><p style=\"text-indent:2em;\">\U4f4f\U767e\U5bb6\U65c5\U6e38\U7ba1\U5bb6(omeome),\U662f\U4e13\U4e3a\U56fd\U4eba\U8bbe\U8ba1\U7684\U5883\U5916\U65c5\U6e38\U77ed\U79df\U670d\U52a1\U5e94\U7528\U3002<br/>           \U4f4f\U767e\U5bb6\U5728\U5168\U740360\U591a\U4e2a\U56fd\U5bb6\U548c\U5730\U533a\U62e5\U6709\U6570\U767e\U4e07\U5957\U4f18\U8d28\U623f\U6e90\Uff0c\U5168\U9762\U8986\U76d6\U4e86\U51fa\U5883\U65c5\U6e38\U7684\U9700\U6c42\U3002<br/>           \U4e0d\U65ad\U66f4\U65b0\U7684\U51fa\U5883\U6e38\U65b0\U73a9\U6cd5\Uff0c\U6253\U9020\U539f\U6c41\U539f\U5473\U7684\U6d77\U5916\U751f\U6d3b\U4f53\U9a8c\U3002</p></div></div>";
            PromotionsId = 144;
            PromotionsStatus = 5;
            PromotionsType = 3;
            Recommend = "<null>";
            RelationId = 39;
            RelationStatus = 0;
            ShareType = 0;
            Thumbnails =             (
                "ky/zhubaijia_608x259.jpg"
            );
            Title = "\U4f4f\U767e\U5bb6-\U51fa\U5883\U6e38\U7cbe\U9009\U77ed\U79df-\U81ea\U7531\U884c\U6c11\U5bbf\U4e13\U5bb6-\U65c5\U884c\U7f8e\U98df\U653b\U7565\U6307\U5357";
        }
    );
    Msg = "\U83b7\U53d6\U6d3b\U52a8\U9996\U9875\U4fe1\U606f";
}

**Comment by zhenyiyi** [comment]
if let b = AnyBidirectionalCollection(properties.children) {
                for i in b.endIndex.advancedBy(-20, limit: b.startIndex)..<b.endIndex {  //因为是继承NSObject对象的，0是NSObject，所以从1开始
                let pro = b[i]
                let key = pro.0        //pro  name
                let type = pro.1  

这个地方有点问题， 如果key对应的 一个数组的 话， 这边的key 打印不出来，搞了一下午了，没有搞好。

**Comment by liuyu827** [comment]
这个位置的问题 可以修改

 if dic != nil{
            if let b = AnyBidirectionalCollection(properties.children) {
                for i in b.endIndex.advancedBy(-20, limit: b.startIndex)..<b.endIndex {  //因为是继承NSObject对象的，0是NSObject，所以从1开始
                let pro = b[i]
                let key = pro.0        //pro  name
                let type = pro.1    // pro type

```
            switch type {
            case _ as Int,_ as Int64,_ as Float,_ as Double,_ as Bool:  //base type
                let value: AnyObject! = dic?.objectForKey(key!)
                if value != nil{
                    obj.setValue(value, forKey: key!)
                }
                break

            case _ as String:
                let value: AnyObject! = dic?.objectForKey(key!)
                if value != nil{
                    obj.setValue(value.description, forKey: key!)
                }
                break

            case _ as Array<String>:  //arr string
                if let nsarray = dic?.objectForKey(key!) as? NSArray {
                    var array:Array<String> = []
                    for el in nsarray {
                        if let typedElement = el as? String {
                            array.append(typedElement)
                        }
                    }
                    obj.setValue(array, forKey: key!)
                }
                break


            case _ as Array<Int>:   //arr int
                if let nsarray = dic?.objectForKey(key!) as? NSArray {
                    var array:Array<Int> = []
                    for el in nsarray {
                        if let typedElement = el as? Int {
                            array.append(typedElement)
                        }
                    }
                    obj.setValue(array, forKey: key!)
                }
                break

            default:     //unknow
```

//                    let clz: AnyClass! = swiftClassFromString(String(stringInterpolationSegment: type))
                    let name:NSString = String(Mirror(reflecting: type).subjectType)
                    let clz:AnyClass! = NSClassFromString(getClassName(name) as String)

```
                if clz != nil{
                    if let data = dic.objectForKey(key!) as? NSArray{
                        let value = jsonToModelList(data, clazz: clz)
                            obj.setValue(value, forKey: key!)
                    }
                    else{
                        obj.setValue(jsonToModel(dic.objectForKey(key!), clazz: clz),forKey:key!)
                    }
                }
                else{
                    print("unknown property")
                }
            }
        }
    }
    }
    else{
        return nil
    }
```

最下边的 else 去掉 就好了

**Comment by mozhenhau** [comment]
@zhenyiyi 不明白，是用的什么数组？Array<T>还是NSArray

**Comment by Heinoc** [comment]
迟点更新，到现在还没有更新呢？

**Comment by mozhenhau** [comment]
@Heinoc  刚更新了，抱歉

**Comment by Heinoc** [comment]
嗯，谢谢，估计你给忙忘了 ^_^
